apiVersion: v1
kind: ConfigMap
metadata:
  name: irango-payment-config
  namespace: irango-payment
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_PORT: "3306"
  DB_DATABASE: "cook"
  DB_CONNECTION_LIMIT: "10000"
  DB_CONNECTION_TIMEOUT: "30000"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_ENABLED: "true"
  CACHE_ENABLED: "true"
  SERVICE_IRANGO_ORDER_API: "irango-api.irango-api.svc.cluster.local:32000"
