apiVersion: v1
kind: ConfigMap
metadata:
  name: irango-payment-config
  namespace: irango-payment
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_PORT: "3306"
  DB_DATABASE: "irango_payment"
  DB_CONNECTION_LIMIT: "10000"
  DB_CONNECTION_TIMEOUT: "30000"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_ENABLED: "true"
  CACHE_ENABLED: "true"
  SNS_TOPIC_PAYMENT_CREATED: "arn:aws:sns:us-east-1:166954469144:fiap-irango-payment_payment-created"
  SNS_TOPIC_PAYMENT_CONFIRMED: "arn:aws:sns:us-east-1:166954469144:fiap-irango-payment_payment-confirmed"
  URL_QUEUE: "https://sqs.us-east-1.amazonaws.com/166954469144/"
  CREATED_ORDER_QUEUE: "fiap-irango-payment_order-created"
