apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: irango-payment-api-hpa
  namespace: irango
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: irango-payment-api
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
