apiVersion: batch/v1
kind: Job
metadata:
  name: irango-payment-api-migration
  namespace: irango
  labels:
    app: irango-payment-api
spec:
  template:
    metadata:
      name:  name
    spec:
      containers:
      - name: irango-payment-api-migration
        image: $IMAGE_URI_PAYMENT
        command: ["/bin/sh", "-c"]
        args:
        - |
          npm run migration:run
          npm run seed:run
        envFrom:
          - secretRef:
              name: irango-payment-api-secret
          - configMapRef:
              name: irango-payment-api-config
      restartPolicy: OnFailure
