apiVersion: v1
kind: ConfigMap
metadata:
  name: irango-cook-config
  namespace: irango-cook
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_PORT: "3306"
  MONGO_DATABASE: "irango_cook"
  DB_CONNECTION_LIMIT: "10000"
  DB_CONNECTION_TIMEOUT: "30000"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_ENABLED: "true"
  CACHE_ENABLED: "true"
  SNS_TOPIC_COOKING_STARTED: "arn:aws:sns:us-east-1:166954469144:fiap-irango-cook_cooking-started"
  SNS_TOPIC_COOKING_FINISHED: "arn:aws:sns:us-east-1:166954469144:fiap-irango-cook_cooking-finished"
  URL_QUEUE: "https://sqs.us-east-1.amazonaws.com/166954469144/"
  CREATED_ORDER_QUEUE: "fiap-irango-cook_order-created"
  CONFIRM_PAYMENT_QUEUE: "fiap-irango-cook_payment-confirmed"