apiVersion: v1
kind: ConfigMap
metadata:
  name: irango-cook-config
  namespace: irango-cook
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_PORT: "3306"
  MONGO_DATABASE: "irango_cook"
  DB_CONNECTION_LIMIT: "10000"
  DB_CONNECTION_TIMEOUT: "30000"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_ENABLED: "true"
  CACHE_ENABLED: "true"
  SERVICE_IRANGO_ORDER_API: "http://irango-api.irango-api.svc.cluster.local:3000"