apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: irango-api-cook-hpa
  namespace: irango-cook
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: irango-api-cook
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
