kind: Service
apiVersion: v1
metadata:
  name: irango-api-cook
  namespace: irango-cook
spec:
  selector:
    app: irango-api-cook
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001