kind: Service
apiVersion: v1
metadata:
  name: irango-cook-api
  namespace: irango
spec:
  selector:
    app: irango-cook-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30003