apiVersion: v1
kind: Secret
metadata:
  name: irango-cook-api-secret
  namespace: irango
type: Opaque
stringData:
  SENTRY_DSN: "$SENTRY_DSN"
  MONGO_HOSTNAME: "$MONGO_HOSTNAME"
  MONGO_USERNAME: "$MONGO_USERNAME"
  MONGO_PASSWORD: "$MONGO_PASSWORD"

  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
