apiVersion: apps/v1
kind: Deployment
metadata:
  name: irango-cook-api
  namespace: irango
  labels:
    app: irango-cook-api
spec:
  selector:
    matchLabels:
      app: irango-cook-api
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 10
  template:
    metadata:
      name: irango-cook-api
      namespace: irango
      labels:
        app: irango-cook-api
        version: "latest"
    spec:
      containers:
        - name: irango-cook-api
          image: $IMAGE_URI_COOK
          livenessProbe:
            httpGet:
              path: /health-check
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "256Mi"
          imagePullPolicy: "Always"
          ports:
          - containerPort: 3000
          envFrom:
          - secretRef:
              name: irango-cook-api-secret
          - configMapRef:
              name: irango-cook-api-config
