apiVersion: v1
kind: Secret
metadata:
  name: irango-secret
  namespace: irango-cook
type: Opaque
stringData:
  SENTRY_DSN: "$SENTRY_DSN"
  MONGO_HOSTNAME: "$MONGO_HOSTNAME"
  MONGO_USERNAME: "$MONGO_USERNAME"
  MONGO_PASSWORD: "$MONGO_PASSWORD"
