apiVersion: v1
kind: ConfigMap
metadata:
  name: irango-config
  namespace: irango
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_PORT: "3306"
  DB_DATABASE: "irango"
  DB_CONNECTION_LIMIT: "10000"
  DB_CONNECTION_TIMEOUT: "30000"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_ENABLED: "true"
  CACHE_ENABLED: "true"
  SNS_TOPIC_ORDER_CREATED: "arn:aws:sns:us-east-1:166954469144:fiap-irango-order_order-created"
  URL_QUEUE: "https://sqs.us-east-1.amazonaws.com/166954469144/"
  START_COOK_QUEUE: "fiap-irango-order_cooking-started"
  START_FINISH_QUEUE: "fiap-irango-order_cooking-finished"
  CONFIRM_PAYMENT_QUEUE: "fiap-irango-order_payment-confirmed"
  CREATED_PAYMENT_QUEUE: "fiap-irango-order_payment-created"