apiVersion: v1
kind: ConfigMap
metadata:
  name: irango-config
  namespace: irango
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_PORT: "3306"
  DB_DATABASE: "irango"
  DB_CONNECTION_LIMIT: "10000"
  DB_CONNECTION_TIMEOUT: "30000"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_ENABLED: "true"
  CACHE_ENABLED: "true"
  SERVICE_IRANGO_PAYMENT_API: "http://irango-api-payment.irango-payment.svc.cluster.local:3000"
  SERVICE_IRANGO_COOK_API: "http://irango-api-cook.irango-cook.svc.cluster.local:3000"